
-- Ensure the DDL runs as the application user created by the container
-- The container sets APP_USER=aedes and APP_USER_PASSWORD=aedes_password
CONNECT aedes/aedes_password@//localhost:1521/XEPDB1
-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(50) UNIQUE NOT NULL,
    name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    base_price NUMBER(10, 2) NOT NULL,
    current_price NUMBER(10, 2) NOT NULL,
    stock NUMBER(10) DEFAULT 0 NOT NULL,
    expiry_date DATE,
    trend_score NUMBER(3) DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_stock_non_negative CHECK (stock >= 0)
);

-- Create TRANSACTIONS table
CREATE TABLE TRANSACTIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    quantity NUMBER(10) NOT NULL,
    sold_price NUMBER(10, 2) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);

-- Trigger to update stock after transaction
CREATE OR REPLACE TRIGGER TRG_UPDATE_STOCK
AFTER INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
    UPDATE PRODUCTS
    SET stock = stock - :NEW.quantity
    WHERE id = :NEW.product_id;
END;
/

-- Stored Procedure: Aedes Pricing Engine (Refactored)
CREATE OR REPLACE PROCEDURE PRC_AEDES_PRICING AS
BEGIN
    FOR r IN (SELECT id, base_price, stock, expiry_date, trend_score FROM PRODUCTS) LOOP
        DECLARE
            new_price NUMBER(10, 2);
            price_multiplier NUMBER(10, 4) := 1.0;
            days_until_expiry NUMBER;
        BEGIN
            days_until_expiry := r.expiry_date - SYSDATE;

            -- Logic 1: Expiry Decay (Only if Expiry Date exists)
            IF r.expiry_date IS NOT NULL THEN
                IF days_until_expiry <= 0 THEN
                     price_multiplier := price_multiplier * 0.1; -- 90% off (Clearance)
                ELSIF days_until_expiry < 3 THEN
                     price_multiplier := price_multiplier * 0.7; -- 30% off
                END IF;
            END IF;

            -- Logic 2: Scarcity Surge
            IF r.stock < 10 THEN
                price_multiplier := price_multiplier * 1.15; -- 15% increase
            END IF;

            -- Logic 3: Trend/Demand Logic
            IF r.trend_score > 80 THEN
                price_multiplier := price_multiplier * 1.25; -- 25% Hype tax
            ELSIF r.trend_score < 20 THEN
                price_multiplier := price_multiplier * 0.95; -- 5% discount
            END IF;

            -- Calculate new price
            new_price := r.base_price * price_multiplier;

            -- Round to 2 decimal places
            new_price := ROUND(new_price, 2);

            -- Update the product
            UPDATE PRODUCTS
            SET current_price = new_price,
                last_updated = CURRENT_TIMESTAMP
            WHERE id = r.id;
        END;
    END LOOP;
    
    COMMIT;
END;
/

-- Insert some dummy data
INSERT INTO PRODUCTS (sku, name, category, base_price, current_price, stock, expiry_date, trend_score) VALUES ('DAIRY-001', 'Organic Whole Milk', 'Dairy', 4.50, 4.50, 45, SYSDATE + 5, 20);
INSERT INTO PRODUCTS (sku, name, category, base_price, current_price, stock, expiry_date, trend_score) VALUES ('ELEC-099', 'GamerHeadset X1', 'Electronics', 120.00, 120.00, 5, SYSDATE + 365, 95);
INSERT INTO PRODUCTS (sku, name, category, base_price, current_price, stock, expiry_date, trend_score) VALUES ('BAKE-102', 'Artisan Sourdough', 'Bakery', 8.00, 8.00, 12, SYSDATE + 2, 50);
INSERT INTO PRODUCTS (sku, name, category, base_price, current_price, stock, expiry_date, trend_score) VALUES ('SNK-555', 'Limited Ed. Chips', 'Snacks', 3.50, 3.50, 200, SYSDATE + 180, 10);
COMMIT;
